services:
  db:
    restart: always
    image: postgres:latest
    ports:
      - "5443:5432"
    environment:
      - POSTGRES_DB=shortener
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6384:6384"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./src/config/dev/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"
    restart: unless-stopped

volumes:
  db:
  redis_data:
  prometheus_data:
